### ISSUE TITLE
the test are all zeros now!

### ISSUE THREAD

**Issue by xwdeng** [ZenProjects/OCRAjs#1]
the response for OCRA are all zeros.

**Comment by mcarbonneaux** [comment]
ho ! there somefing changed in jsSHA lib, or in navigator !

**Comment by mcarbonneaux** [comment]
no is related to rawgit cdn... i now use github jekil to server javascript!
and now you have jsSHA engine test execution page and sjcl engine test execution page !

**Comment by mcarbonneaux** [comment]
in fact is realy jsSHA engine probleme... i need to investigate why... somefine has changed in engine...
